# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2

      - name: Set up Python all python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64

      - name: Install Python Virtual ENV
        run: pip install virtualenv

      - name: Install Dependencies into Virtual env
        run: python -m venv venv  
        
      - name: Activate Virtual env
        run: venv/bin/activate 

      # Install all the app dependencies
      - name: Install dependencies
        run: pip freeze > requirements.txt


      # Build the app and run tests
      - name: Build and Run Test
        run: . venv/bin/activate 

      - name: Create Zipfile archive of Dependencies
        run: |
          cd ./venv/lib/python3.9/site-packages
          zip -r9 ../../../../api.zip .

      - name: Add App to Zipfile
        run: ./app && zip -g ../api.zip -r .

      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: api.zip

